# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v9.5.0
_src_path: https://github.com/Tecnativa/doodba-copier-template
backup_dst: ''
cidr_whitelist: null
compose_version: v2+
domains_migration: {}
domains_prod: []
domains_test:
- test-portal.alimentosdelsur.com
- test-alimentosdelsur.cumbre.ar
gitlab_url: ''
odoo_dbfilter: ^test
odoo_initial_lang: es_AR
odoo_listdb: false
odoo_listdb_staging: false
odoo_oci_image: docker.io/marionumza/do-alimentosdelsur16ce
odoo_proxy: traefik
odoo_version: 16.0
paths_with_crawlers:
- /web/image/website
paths_without_crawlers:
- /web
- /website/info
postgres_dbname: test
postgres_exposed: false
postgres_username: odoo
postgres_version: '18'
project_author: Crumges
project_license: BSL-1.0
project_name: do-alimentosdelsur16ce
smtp_default_from: ''
smtp_relay_host: ''
traefik_version: 2
use_refurb: false
whitelist_docker_project_devel: do-alimentosdelsur16ce
whitelisted_hosts_devel:
- cdnjs.cloudflare.com
- fonts.googleapis.com
- fonts.gstatic.com
- www.google.com
- www.googleapis.com
- www.gravatar.com
whitelisted_hosts_test: []

